name: Format and lint code
on:
  pull_request:
permissions:
  contents: write
jobs:
  format_and_lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Run Black
        uses: psf/black@stable
      - name: Run Flake8
        run: flake8 .
